<?xml version="1.0" encoding="utf-8"?>
<run passed="0" failed="1" unexecuted="0" time="1521" total="1">
  <tests>
    <test key=".\GetEmployee-direct-call" name="GetEmployee-direct-call" outcome="failed" time="212">
      <step id="2YNMAVi0DVdcFF8929mldL" name="setLoop" outcome="passed" time="48">
        <action id="6kNQMfLFMtwYTvgA7K74gm" type="coded-step" outcome="passed" time="20" />
      </step>
      <step id="1EgNTIYf7IUKEAiJqnOHhs" name="Http Request" outcome="failed" time="52">
        <action id="4QvGvLYuWaDFExRFypHMDP" type="http-request" outcome="failed" time="51">
          <error message="Invalid URI: The URI is empty." />
        </action>
      </step>
    </test>
  </tests>
  <output>
    <output message="The test case is starting ..." />
    <output message="Create Excel Result File" />
    <output message="Time of starting Test :: _17012023_10_21_20" />
    <output message="URL :: " />
    <output message="loop-value :: 2" />
    <output message="File Not Find" />
    <output message="" />
    <output message="Ending the test case ..." />
  </output>
  <errors>
    <error message="Running test's 'OnAfterTestCompleted' method failed. Message: 'Index was outside the bounds of the array.'" />
  </errors>
</run>